name: Run E2E Tests

on: [pull_request] # Dispara o workflow em cada pull request

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest # Define o ambiente de execução

    services:
      postgres: # Configura o serviço de banco de dados PostgreSQL
        image: bitnami/postgresql
        ports: 
          - '5432:5432'
        environment:
          - POSTGRESQL_USERNAME=docker
          - POSTGRESQL_PASSWORD=docker
          - POSTGRESQL_DATABASE=apisolid

    steps:
      - uses: actions/checkout@v3 # Baixa o código

      - uses: actions/setup-node@v3
        with:
          node-version: 18 # Define a versão do Node.js
          cache: 'npm' # Habilita o cache do npm
      
      - run: npm ci  # Instala as dependências

      - run: npm run test:e2e # Executa os testes E2E
        environment: 
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
